### ISSUE TITLE
Allow lowercase permissions

### ISSUE THREAD

**Issue by michaeltandecki** [raito-io/cli-plugin-snowflake#42]
Currently the `raito access` command does not like this configuration
```
accessProviders:
  -
    name: TESTROLE1
    description: A first role for testing
    access:
      - 
        namingHint: "DATA_SCIENTIST"
        who:
          users:
            - JOBS_DE
        what:
          - dataObject:
              type: table
              fullName: EXTERNAL.PUBLIC_DATASETS.ADULT
            permissions:
              - select
```
because `select` is lowercase. Also, `USAGE` on EXTERNAL and  on EXTERNAL.PUBLIC_DATASETS is generated. The select initially as well, but then it's revoked.

Detail:
Even when correctly having `SELECT` in the config the warning
```
2022-09-16T16:48:13.053+0200 [WARN]  raito-cli.cli-plugin-snowflake-0.5.2: Unknown raito permission "SELECT" found. Mapping as is: iteration=0 target=snowflake1 timestamp="2022-09-16T16:48:13.052+0200"
```
is displayed.
